services:
   vote:
      image: iv41879/vote:latest
      ports:
        - 5000:80

   redis:
     image: redis:alpine

   db:
     image: postgres:9.4

   result:
     image: iv41879/result:latest
     ports:
       - 5001:4000

   worker:
     image: iv41879/worker:latest
